# Generated by Django 4.1.2 on 2022-11-01 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_actions_comments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 11, 1, 12, 17, 32, 770157)),
        ),
        migrations.AddField(
            model_name='actions',
            name='describe',
            field=models.CharField(default='Describe', max_length=200),
        ),
        migrations.AddField(
            model_name='actions',
            name='image',
            field=models.CharField(default='url', max_length=300),
        ),
    ]
