# Generated by Django 4.1.2 on 2022-11-09 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_actions_number_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='author',
            field=models.ForeignKey(default='Nogueira23', on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
