# Generated by Django 4.1.2 on 2022-11-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_actions_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='author',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
