# Generated by Django 4.1.2 on 2022-11-10 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_actions_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='UserAuthor', to=settings.AUTH_USER_MODEL),
        ),
    ]
