# Generated by Django 4.1.2 on 2022-11-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_actions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='author',
        ),
    ]
