# Generated by Django 4.1.2 on 2022-11-10 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_actions_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productOfBid', to='auctions.actions'),
        ),
    ]
