# Generated by Django 4.1.2 on 2022-11-14 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bids_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_commented', to='auctions.actions'),
        ),
    ]
